theme: minima
title: RunAsh 
author: RunAsh Digital Innovation Technologies<br>Private Limited
email: admin@runash.in
description: > # About. Contact. Support. Privacy.  "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: runashstartup # DO NOT include the @ character, or else the build will fail!
github_username:  runash # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
